name: example
description: This is an example on how to use the ezlogin package and how to build an improve User structure on it

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ezlogin: ^1.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.4

dependency_overrides:
  ezlogin:
    path: ../
  enhanced_containers_foundation:
    path: ../external/enhanced_containers_foundation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
